kind = "web"
previewPath = "/"
title = "Pakan Ternak"
version = "1.0.0"
id = "artifacts/mobile"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 22463

[services.development]
run = "pnpm --filter @workspace/mobile run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/mobile", "run", "build" ]
publicDir = "artifacts/mobile/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "22463"
BASE_PATH = "/"
